### PR TITLE
Allow execution of pre-built macos binary on M1

### PR DESCRIPTION
**Pull request by dominicletz**
Added the rosetta translation hint to the embedded plist file. This can be removed once macos arm universal executables are fully supported (don't end in segfaults)

### CODE REVIEW

**Comment by wojtekmach** [comment]
Awesome!

**Comment by wojtekmach** [comment]
@dominicletz I just tried running the executable on my M1 and unfortunately got the segfault. I got the build from https://github.com/erlang/otp/pull/5036/checks, the "Artifacts" links. If you have an access to M1 machine, could you give that a go?

**Comment by dominicletz** [comment]
Same here :-(, for some reason this fix that worked for my production binaries (but older otp branch) didn't work here.

**Comment by wojtekmach** [comment]
What was the OTP branch that you compiled against and it worked?

**Comment by dominicletz** [comment]
We're using this branch for our production builds (which runs on M1) https://github.com/diodechain/otp/tree/diode/beta

But we're also packaging our own plist file and I've copied that `LSArchitecturePriority` section from there into the otp plist -- but maybe I missed something? Or something else has changed so that it doesn't take effect?. Our full production plist is here:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>Diode Drive</string>
	<key>CFBundleDisplayName</key>
	<string>Diode Drive</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>run</string>
	<key>CFBundleIconFile</key>
	<string>icons.icns</string>
	<key>CFBundleIdentifier</key>
	<string><%= @package.identifier %></string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string><%= @release.version %></string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string><%= @release.version %></string>
	<key>LSMinimumSystemVersion</key>
	<string>10.12.0</string>
    <key>LSEnvironment</key>
    <dict>
        <key>DYLD_LIBRARY_PATH</key>
        <string>value</string>
    </dict>
	<key>LSApplicationCategoryType</key>
	<string><%= @package.category_macos %></string>
	<key>LSUIElement</key>
	<true/>
	<key>LSMultipleInstancesProhibited</key>
	<true/>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>LSArchitecturePriority</key>
	<array>
		<string>x86_64</string>
	</array>
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeName</key>
			<string>All Files</string>
			<key>LSHandlerRank</key>
			<string>Alternate</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>public.data</string>
				<string>public.content</string>
			</array>
		</dict>
	</array>	
</dict>
</plist>
```

**Comment by wojtekmach** [comment]
Thanks for the info, will do some more testing. Looks like you're basically using OTP-24.0-rc1 so that's good to know. I'll try to test against latest 24.0.x soon. One thing that comes to mind is OTP master is using updated asmjit with support for arm Macs, so that is a potential culprit.

**Comment by wojtekmach** [comment]
@dominicletz no luck on 24.0.5. I also tried basically your branch but no luck either. This is the last thing I tried: https://github.com/wojtekmach/otp/commits/wm-rosetta

I'm building it on:

```
$ uname -a
Darwin iMac-Wojtek.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

and trying to run on:

```
$ uname -a
Darwin macbookair.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

there's a different kernel version so maybe that is the difference.

If you have a branch with all plist patches and whatnot applied, I'd be happy to test it out.

**Comment by dominicletz** [comment]
From what I'm reading the plist file only has an effect on Finder launched Apps, so that might be the issue here. You can seemingly force it to run through rosetta using `arch -x86_64 <command>` command but to make it launch x86_64 by default from terminal I see these options

* Completely remove the arm code so that it does not run that broken code (if that is a possible venue) 
* Add the `arch -x86_64 -x86_64` to the erlexec script on macos

**Comment by wojtekmach** [comment]
yeah I have a special rosetta-enabled iTerm:

image

```
$ uname -a
Darwin macbookair.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64
$ arch
i386
```

but no luck there either :(

**Pull request merged**
